name: CARA ALEXANDER
favicon: null
layout_spectrum: 0.7058591258246452
typography_spectrum: 0.6378387885633856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3167261516209692
  lightness: 0.48249812866561115
  saturation: 0.25401237048208714
  rhythmicContrast: 0.7131241967435926
purpose: []
